import type { Metadata } from "next";
import "./globals.css";
import "@/components/header"; // これいるか？
import Header from "@/components/header";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "mf7cli's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="transition-colors duration-500 text-slate-950 dark:text-slate-50 bg-white dark:bg-neutral-950">
        <Providers>
          <Header />
          {children}
          <footer className="flex justify-center m-10 p-5 border-t-2 border-neutral-100 dark:border-neutral-900">© 2024 mf7cli</footer>
        </Providers>
      </body>
    </html>
  );
}
