import type { Metadata } from "next";
import { M_PLUS_1p } from "next/font/google";
import "./globals.css";
import "@/components/header";
import Header from "@/components/header";

const m_PLUS_1p300 = M_PLUS_1p({ 
  subsets: ["latin"], 
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
        <footer className="flex justify-center m-10">© 2024 mf7cli</footer>
      </body>
    </html>
  );
}
